# Generated by Django 4.0.2 on 2022-10-18 17:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_alter_comment_managers'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='comment',
            managers=[
            ],
        ),
    ]
